<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Display.aspx.cs" Inherits="CRUD_ASP.Display" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            </div>
        <div>
            <br />
            <asp:Label ID="lbl_coursename1" runat="server" Text="Course Name"></asp:Label>
            <asp:DropDownList runat="server" ID="DDL_Course" AutoPostBack="True"></asp:DropDownList>
            &nbsp;<br />
            <br />
            <asp:Label ID="lbl_coursenm" runat="server" Text="Course Name"></asp:Label>
&nbsp;<asp:TextBox ID="txt_coursenm" runat="server"></asp:TextBox>
            <br />
            <br />
            <asp:Label ID="Label2" runat="server" Text="Dept Name"></asp:Label>
&nbsp;<asp:DropDownList ID="DDL_Dept" runat="server" AutoPostBack="true" OnSelectedIndexChanged="DDL_Dept_SelectedIndexChanged"></asp:DropDownList>
            <br />
            <br />
            <asp:Button ID="btn_Inset" runat="server" OnClick="btn_Inset_Click" Text="INSERT" />
&nbsp;<asp:Button ID="btn_Update" runat="server" OnClick="btn_Update_Click" Text="UPDATE" />
            &nbsp;<asp:Button ID="btn_delete" runat="server" OnClick="btn_delete_Click" Text="DELETE" />
            <asp:Button ID="Button1" runat="server" OnClick="Button1_Click" Text="Button" />
            <br />
        </div>

        <div>
            <asp:GridView ID="GridView1" runat="server" AutoGenerateDeleteButton="True" AutoGenerateSelectButton="True" OnSelectedIndexChanged="GridView1_SelectedIndexChanged" OnRowDeleting="GridView1_RowDeleting" DataKeyNames="Course_id" AutoGenerateEditButton="True" OnRowCancelingEdit="GridView1_RowCancelingEdit" OnRowEditing="GridView1_RowEditing" OnRowUpdating="GridView1_RowUpdating"></asp:GridView>
        </div>
    </form>
</body>
</html>
